import { readFileSync } from 'node:fs';
import { describe, expect, test } from 'vitest';

describe('/stkde-3d route focus mode', () => {
  test('exposes a single-slice toggle and detail inspector', () => {
    const pageSource = readFileSync(new URL('./page.tsx', import.meta.url), 'utf8');
    const sceneSource = readFileSync(new URL('./components/Stkde3DScene.tsx', import.meta.url), 'utf8');
    const inspectorSource = readFileSync(new URL('./components/SliceInspector.tsx', import.meta.url), 'utf8');
    const stackSource = readFileSync(new URL('./components/StkdeSliceStack.tsx', import.meta.url), 'utf8');
    const comparisonSource = readFileSync(new URL('./components/StkdeComparisonControls.tsx', import.meta.url), 'utf8');
    const comparisonStageSource = readFileSync(new URL('./components/StkdeComparisonStage.tsx', import.meta.url), 'utf8');
    const comparisonViewportSource = readFileSync(new URL('./components/StkdeComparisonViewport.tsx', import.meta.url), 'utf8');
    const differenceSource = readFileSync(new URL('./components/StkdeDifferenceScene.tsx', import.meta.url), 'utf8');
    const differenceLegendSource = readFileSync(new URL('./components/StkdeSignedDifferenceLegend.tsx', import.meta.url), 'utf8');
    const cameraSource = readFileSync(new URL('./lib/comparison-camera.ts', import.meta.url), 'utf8');
    const providerSource = readFileSync(new URL('./components/Stkde3DSceneProvider.tsx', import.meta.url), 'utf8');
    const sourceContextSource = readFileSync(new URL('./lib/comparison-source-context.ts', import.meta.url), 'utf8');

    expect(pageSource).toMatch(/Single slice/);
    expect(pageSource).toMatch(/Stack view/);
    expect(pageSource).toMatch(/Active events/);
    expect(pageSource).toMatch(/Trajectories/);
    expect(pageSource).toMatch(/Adaptive time/);
    expect(pageSource).toMatch(/Grid field/);
    expect(pageSource).toMatch(/Legacy blobs/);
    expect(pageSource).toMatch(/SliceInspector/);
    expect(pageSource).toMatch(/viewMode={isFocusedView \? 'focus' : 'stack'}/);
    expect(pageSource).toMatch(/sliceEvents={sliceEvents}/);
    expect(pageSource).toMatch(/showRawEvents={showRawEvents}/);
    expect(pageSource).toMatch(/setIsPlaying\(false\)/);
    expect(pageSource).toMatch(/createStkde3DSceneRuntime/);
    expect(pageSource).toMatch(/sourceSliceId/);
    expect(pageSource).toMatch(/timeDomain/);
    expect(pageSource).toMatch(/buildStandaloneAdaptiveTimeMaps/);
    expect(pageSource).toMatch(/StandaloneSliceScrubber/);
    expect(pageSource).toMatch(/setIsFocusedView\(false\)/);
    expect(pageSource).toMatch(/setComparison\(exitComparison\(\)\)/);
    expect(pageSource).toMatch(/StkdeComparisonStage/);
    expect(pageSource).toMatch(/comparisonSelectionEnabled: comparison\?\.mode === 'selecting'/);
    expect(pageSource).not.toMatch(/useDashboardDemoCoordinationStore|useDashboardDemoTimeslicingModeStore|useSliceDomainStore|useViewportStore/);
    expect(sceneSource).toMatch(/viewMode\?: 'stack' \| 'focus'/);
    expect(sceneSource).toMatch(/showRawEvents\?: boolean/);
    expect(sceneSource).toMatch(/sliceEvents\?: MockCrimeEvent\[\]\[]/);
    expect(sceneSource).toMatch(/compact={viewMode === 'focus'}/);
    expect(sceneSource).toMatch(/RawEventPoints/);
    expect(sceneSource).toMatch(/showHotspotTrajectories/);
    expect(stackSource).toMatch(/compact\?: boolean/);
    expect(stackSource).toMatch(/sourceSliceIndex/);
    expect(stackSource).toMatch(/onComparisonSliceSelect/);
    expect(stackSource).toMatch(/comparisonSelectionEnabled/);
    expect(comparisonSource).toMatch(/Compare intervals/);
    expect(comparisonSource).toMatch(/Select interval A/);
    expect(comparisonSource).toMatch(/Select interval B/);
    expect(comparisonSource).toMatch(/Reset comparison/);
    expect(comparisonSource).toMatch(/Back to stack/);
    expect(comparisonSource).toMatch(/aria-live="polite"/);
    expect(providerSource).toMatch(/onComparisonSliceSelect/);
    expect(providerSource).toMatch(/comparisonSelectionEnabled/);
    expect(sourceContextSource).toMatch(/resolveComparisonSourceContext/);
    expect(comparisonStageSource).toMatch(/data-comparison-stage/);
    expect(comparisonStageSource).toMatch(/data-comparison-mode={mode}/);
    expect(comparisonStageSource).toMatch(/StkdeDifferenceScene/);
    expect(comparisonStageSource).toMatch(/mode === 'difference'/);
    expect(comparisonStageSource).toMatch(/grid-rows-\[minmax\(20rem,1fr\)_minmax\(20rem,1fr\)\]/);
    expect(comparisonStageSource).toMatch(/Stkde3DMapCapture/);
    expect(comparisonStageSource).toMatch(/StkdeSignedDifferenceLegend/);
    expect(differenceSource).toMatch(/computeSignedKdeDifference/);
    expect(differenceSource).toMatch(/data-difference-field="signed-kde"/);
    expect(differenceSource).not.toMatch(/StkdeSliceStack|RawEventPoints|HotspotTrajectoryOverlay|BurstVolumeRenderer|AdaptiveWarpAxis/);
    expect(differenceLegendSource).toMatch(/B higher/);
    expect(differenceLegendSource).toMatch(/0 \/ no difference/);
    expect(differenceLegendSource).toMatch(/A higher/);
    expect(comparisonViewportSource).toMatch(/resolveComparisonSourceContext/);
    expect(comparisonViewportSource).toMatch(/data-interval-slot/);
    expect(comparisonViewportSource).toMatch(/selectedSourceIndex/);
    expect(comparisonViewportSource).toMatch(/CameraControls/);
    expect(cameraSource).toMatch(/setLookAt/);
    expect(cameraSource).toMatch(/snapBToA/);
    expect(cameraSource).toMatch(/applyingMirror/);
    expect(inspectorSource).toMatch(/Clock range/);
    expect(inspectorSource).toMatch(/Burstiness/);
    expect(sceneSource).not.toMatch(/useDashboardDemoCoordinationStore|useDashboardDemoTimeslicingModeStore|useSliceDomainStore|useViewportStore/);
  });
});
