import { readFileSync } from 'node:fs';
import { describe, expect, test } from 'vitest';

describe('/stkde-3d route focus mode', () => {
  test('exposes a single-slice toggle and detail inspector', () => {
    const pageSource = readFileSync(new URL('./page.tsx', import.meta.url), 'utf8');
    const sceneSource = readFileSync(new URL('./components/Stkde3DScene.tsx', import.meta.url), 'utf8');
    const inspectorSource = readFileSync(new URL('./components/SliceInspector.tsx', import.meta.url), 'utf8');
    const stackSource = readFileSync(new URL('./components/StkdeSliceStack.tsx', import.meta.url), 'utf8');
    const comparisonSource = readFileSync(new URL('./components/StkdeComparisonControls.tsx', import.meta.url), 'utf8');
    const comparisonStageSource = readFileSync(new URL('./components/StkdeComparisonStage.tsx', import.meta.url), 'utf8');
    const comparisonViewportSource = readFileSync(new URL('./components/StkdeComparisonViewport.tsx', import.meta.url), 'utf8');
    const comparisonMapSource = readFileSync(new URL('./components/StkdeComparisonFieldMap.tsx', import.meta.url), 'utf8');
    const comparisonMathSource = readFileSync(new URL('./lib/comparison-map.ts', import.meta.url), 'utf8');
    const differenceSource = readFileSync(new URL('./components/StkdeDifferenceScene.tsx', import.meta.url), 'utf8');
    const intensityLegendSource = readFileSync(new URL('./components/StkdeIntensityLegend.tsx', import.meta.url), 'utf8');
    const differenceLegendSource = readFileSync(new URL('./components/StkdeSignedDifferenceLegend.tsx', import.meta.url), 'utf8');
    const cameraSource = readFileSync(new URL('./lib/comparison-camera.ts', import.meta.url), 'utf8');
    const loaderSource = readFileSync(new URL('./lib/dataset-loader.ts', import.meta.url), 'utf8');
    const providerSource = readFileSync(new URL('./components/Stkde3DSceneProvider.tsx', import.meta.url), 'utf8');
    const sourceContextSource = readFileSync(new URL('./lib/comparison-source-context.ts', import.meta.url), 'utf8');

    expect(pageSource).toMatch(/Single slice/);
    expect(pageSource).toMatch(/Stack view/);
    expect(pageSource).toMatch(/Active events/);
    expect(pageSource).toMatch(/Trajectories/);
    expect(pageSource).toMatch(/Adaptive time/);
    expect(pageSource).toMatch(/Grid field/);
    expect(pageSource).toMatch(/Legacy blobs/);
    expect(pageSource).toMatch(/SliceInspector/);
    expect(pageSource).toMatch(/viewMode={isFocusedView \? 'focus' : 'stack'}/);
    expect(pageSource).toMatch(/sliceEvents={sliceEvents}/);
    expect(pageSource).toMatch(/showRawEvents={showRawEvents}/);
    expect(pageSource).toMatch(/setIsPlaying\(false\)/);
    expect(pageSource).toMatch(/createStkde3DSceneRuntime/);
    expect(pageSource).toMatch(/sourceSliceId/);
    expect(pageSource).toMatch(/timeDomain/);
    expect(pageSource).toMatch(/buildStandaloneAdaptiveTimeMaps/);
    expect(pageSource).toMatch(/StandaloneSliceScrubber/);
    expect(pageSource).toMatch(/setIsFocusedView\(false\)/);
    expect(pageSource).toMatch(/setComparison\(exitComparison\(\)\)/);
    expect(pageSource).toMatch(/StkdeComparisonStage/);
    expect(pageSource).toMatch(/comparisonSelectionEnabled: comparison\?\.mode === 'selecting'/);
    expect(pageSource).not.toMatch(/useDashboardDemoCoordinationStore|useDashboardDemoTimeslicingModeStore|useSliceDomainStore|useViewportStore/);
    expect(sceneSource).toMatch(/viewMode\?: 'stack' \| 'focus'/);
    expect(sceneSource).toMatch(/showRawEvents\?: boolean/);
    expect(sceneSource).toMatch(/sliceEvents\?: MockCrimeEvent\[\]\[]/);
    expect(sceneSource).toMatch(/compact={viewMode === 'focus'}/);
    expect(sceneSource).toMatch(/RawEventPoints/);
    expect(sceneSource).toMatch(/showHotspotTrajectories/);
    expect(stackSource).toMatch(/compact\?: boolean/);
    expect(stackSource).toMatch(/sourceSliceIndex/);
    expect(stackSource).toMatch(/onComparisonSliceSelect/);
    expect(stackSource).toMatch(/comparisonSelectionEnabled/);
    expect(comparisonSource).toMatch(/Compare intervals/);
    expect(comparisonSource).toMatch(/Select interval A/);
    expect(comparisonSource).toMatch(/Select interval B/);
    expect(comparisonSource).toMatch(/Reset comparison/);
    expect(comparisonSource).toMatch(/Back to stack/);
    expect(comparisonSource).toMatch(/activateComparisonSlot/);
    expect(comparisonSource).toMatch(/aria-pressed/);
    expect(comparisonSource).toMatch(/aria-selected/);
    expect(comparisonSource).toMatch(/<select/);
    expect(comparisonSource).toMatch(/aria-live="polite"/);
    expect(comparisonSource).not.toMatch(/Rendered intervals/);
    expect(comparisonSource).not.toMatch(/source:/);
    expect(providerSource).toMatch(/onComparisonSliceSelect/);
    expect(providerSource).toMatch(/comparisonSelectionEnabled/);
    expect(sourceContextSource).toMatch(/resolveComparisonSourceContext/);
    expect(comparisonStageSource).toMatch(/data-comparison-stage/);
    expect(comparisonStageSource).toMatch(/data-comparison-mode={mode}/);
    expect(comparisonStageSource).toMatch(/A\/B COMPARISON/);
    expect(comparisonStageSource).toMatch(/Shared absolute domain/);
    expect(comparisonStageSource).toMatch(/KDE\(A\) − KDE\(B\) · signed difference/);
    expect(comparisonStageSource).toMatch(/StkdeDifferenceScene/);
    expect(comparisonStageSource).toMatch(/mode === 'difference'/);
    expect(comparisonStageSource).toMatch(/grid-rows-\[minmax\(20rem,1fr\)_minmax\(20rem,1fr\)\]/);
    expect(comparisonStageSource).toMatch(/grid-cols-1/);
    expect(comparisonStageSource).toMatch(/StkdeIntensityLegend/);
    expect(comparisonStageSource).toMatch(/Stkde3DMapCapture/);
    expect(comparisonStageSource).toMatch(/StkdeSignedDifferenceLegend/);
    expect(comparisonStageSource).toMatch(/slot="A"/);
    expect(comparisonStageSource).toMatch(/slot="B"/);
    expect((comparisonStageSource.match(/resolveComparisonSourceContext/g) ?? []).length).toBeGreaterThanOrEqual(2);
    expect(comparisonStageSource).not.toMatch(/CameraControls|cameraController|onModeChange/);
    expect(differenceSource).toMatch(/computeSignedKdeDifference/);
    expect(differenceSource).toMatch(/data-difference-field="signed-kde"/);
    expect(differenceSource).toMatch(/w-full/);
    expect(differenceSource).toMatch(/min-h-\[20rem\]/);
    expect(differenceSource).not.toMatch(/StkdeSliceStack|RawEventPoints|HotspotTrajectoryOverlay|BurstVolumeRenderer|AdaptiveWarpAxis|CameraControls|Top-down spatial field/);
    expect(intensityLegendSource).toMatch(/STKDE INTENSITY/);
    expect(intensityLegendSource).toMatch(/getStkdePaletteGradient/);
    expect(differenceLegendSource).toMatch(/B HIGHER/);
    expect(differenceLegendSource).toMatch(/0 \/ NO DIFFERENCE/);
    expect(differenceLegendSource).toMatch(/A HIGHER/);
    expect(differenceLegendSource).toMatch(/Blue means B higher/);
    expect(comparisonViewportSource).toMatch(/data-interval-slot/);
    expect(comparisonViewportSource).toMatch(/StkdeComparisonFieldMap/);
    expect(comparisonViewportSource).toMatch(/w-full/);
    expect(comparisonViewportSource).toMatch(/min-h-\[20rem\]/);
    expect(comparisonViewportSource).toMatch(/rounded-2xl/);
    expect(comparisonViewportSource).not.toMatch(/CameraControls|Stkde3DScene|selectedSourceIndex/);
    expect(comparisonMapSource).toMatch(/displayMode/);
    expect(comparisonMapSource).toMatch(/mapSignedContrast/);
    expect(comparisonMapSource).toMatch(/items-center justify-center/);
    expect(comparisonMapSource).toMatch(/aspect-\[16\/7\]/);
    expect(comparisonMapSource).toMatch(/max-w-\[72rem\]/);
    expect(comparisonMathSource).toMatch(/COMPARISON_MAP_EXTENT = 100/);
    expect(comparisonMathSource).toMatch(/Math\.pow\(Math\.abs\(ratio\), 0\.65\)/);
    expect(cameraSource).toMatch(/setLookAt/);
    expect(cameraSource).toMatch(/snapBToA/);
    expect(cameraSource).toMatch(/applyingMirror/);
    expect(inspectorSource).toMatch(/Clock range/);
    expect(inspectorSource).toMatch(/Burstiness/);
    expect(sceneSource).not.toMatch(/useDashboardDemoCoordinationStore|useDashboardDemoTimeslicingModeStore|useSliceDomainStore|useViewportStore/);
  });

  test('wires exact preset resolution, dataset invalidation, and signed-mode gating', () => {
    const pageSource = readFileSync(new URL('./page.tsx', import.meta.url), 'utf8');
    const controlsSource = readFileSync(new URL('./components/StkdeComparisonControls.tsx', import.meta.url), 'utf8');
    const presetSource = readFileSync(new URL('./lib/comparison-presets.ts', import.meta.url), 'utf8');
    const fixtureSource = readFileSync(new URL('./lib/comparison-fixtures.ts', import.meta.url), 'utf8');
    const differenceSource = readFileSync(new URL('./components/StkdeDifferenceScene.tsx', import.meta.url), 'utf8');
    const loaderSource = readFileSync(new URL('./lib/dataset-loader.ts', import.meta.url), 'utf8');

    expect(pageSource).toMatch(/COMPARISON_PRESETS/);
    expect(pageSource).toMatch(/resolveComparisonPreset/);
    expect(pageSource).toMatch(/pendingComparisonPresetId/);
    expect(pageSource).toMatch(/activateComparisonSlot/);
    expect(pageSource).toMatch(/activeSlot: null/);
    expect(pageSource).toMatch(/setDataset\(null\)/);
    expect(pageSource).toMatch(/invalidateComparison\(\)/);
    expect(pageSource).toMatch(/loadStkde3dDataset\(preset\)/);
    expect(loaderSource).toMatch(/fetchImpl/);
    expect((loaderSource.match(/\/api\/crimes\/range/g) ?? []).length).toBe(1);
    expect(controlsSource).toMatch(/Comparison preset/);
    expect(controlsSource).toMatch(/A \{preset\.intervalA\.label\} vs B \{preset\.intervalB\.label\}/);
    expect(presetSource).toMatch(/full-slice-02-vs-08/);
    expect(presetSource).toMatch(/fourth-of-july-slice-03-vs-09/);
    expect(fixtureSource).toMatch(/buildComparisonSliceFixture/);
    expect(differenceSource).toMatch(/computeSignedKdeDifference/);
    expect(differenceSource).not.toMatch(/showRawEvents|showHotspotTrajectories|StkdeSliceStack|HotspotTrajectoryOverlay|BurstVolumeRenderer|AdaptiveWarpAxis/);
  });
});
