import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const FORBIDDEN_MODULES = [
  "duckdb",
  "three",
  "@react-three/fiber",
  "@react-three/drei",
  "@deck.gl/core",
  "@deck.gl/aggregation-layers",
  "@deck.gl/mapbox",
  "@deck.gl/react",
  "maplibre-gl",
  "react-map-gl",
  "react-leaflet",
  "react-leaflet-markercluster",
  "leaflet",
  "leaflet-draw",
  "leaflet.markercluster",
  "leaflet.fullscreen",
  "apache-arrow",
  "density-clustering",
  "driver.js",
  "cmdk",
  "@loaders.gl/arrow",
  "@loaders.gl/core",
  "@math.gl/web-mercator",
];

const FORBIDDEN_PATH_PATTERNS = [
  "@/app/algorithms",
  "@/app/cube-sandbox",
  "@/app/dashboard-demo",
  "@/app/demo",
  "@/app/docs",
  "@/app/evaluation",
  "@/app/figures",
  "@/app/hotspot-evolution",
  "@/app/stats",
  "@/app/stkde",
  "@/app/stkde-3d",
  "@/app/timeline-test",
  "@/app/timeline-test-3d",
  "@/app/timeslicing",
  "@/app/timeslicing-algos",
  "@/app/api",
  "@/lib/study",
  "@/lib/adaptive",
  "@/lib/binning",
  "@/lib/clustering",
  "@/lib/cohort",
  "@/lib/demographics",
  "@/lib/mapbox",
  "@/lib/stkde",
  "@/lib/synthetic",
  "@/lib/tessellation",
  "@/store/useStudyStore",
  "@/store/useEvaluationStudyStore",
  "@/store/useStkdeStore",
  "@/store/useDashboardDemoCoordinationStore",
  "@/components/map",
  "@/components/charts",
  "@/components/cube",
  "@/components/cube-sandbox",
  "@/components/dashboard",
  "@/components/dashboard-v2",
  "@/components/demo",
  "@/components/figures",
  "@/components/hotspot",
  "@/components/stkde",
  "@/components/stkde-3d",
  "@/components/timeline",
  "@/components/timeslicing",
  "@/components/timeslicing-algos",
  "@/components/onboarding",
  "@/components/layout",
  "@/hooks/useClusterAnalysis",
  "@/hooks/useStkde",
  "@/hooks/useCubeSandbox",
  "@/hooks/useAdaptive",
  "@/hooks/useCoordination",
  "@/hooks/useCoordinationStore",
  "@/hooks/useDashboardDemo",
  "@/workers",
];

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  {
    files: ["src/lib/ats-study/**/*.{ts,tsx}", "src/components/study/**/*.{ts,tsx}", "src/app/experiment/**/*.{ts,tsx}", "src/app/page.tsx", "src/app/layout.tsx"],
    rules: {
      "no-restricted-imports": [
        "error",
        {
          paths: FORBIDDEN_PATH_PATTERNS.map((name) => ({ name, message: "Forbidden: prototype module/import on the ats-study branch." })),
          patterns: FORBIDDEN_MODULES.map((name) => ({
            group: [`${name}`, `${name}/*`],
            message: `Forbidden: ${name} cannot appear in the study bundle.`,
          })),
        },
      ],
    },
  },
  globalIgnores([
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    "datapreprocessing/.venv/**",
  ]),
]);

export default eslintConfig;
