// Hand-written stub for the Convex `api.ts` and `internal` registries. In a
// real Convex project these are regenerated by `npx convex dev` based on the
// exports of files in `convex/`. The current stub is empty because no
// functions have been referenced by other Convex functions yet — when the
// Convex project is provisioned, the codegen will populate it automatically.

import type { FunctionReference } from "convex/server";

export const api = {} as Record<string, Record<string, FunctionReference<"query" | "mutation" | "action", "public", Record<string, never>, unknown>>>;
export const internal = {} as Record<string, Record<string, FunctionReference<"query" | "mutation" | "action", "internal", Record<string, never>, unknown>>>;
